### PR TITLE
Add Terminus support

### PR DESCRIPTION
**Pull request by rastersoft**
This patch adds support for Terminus: https://www.rastersoft.com/programas/terminus.html

### CODE REVIEW

**Comment by Stunkymonkey** [comment]
@rastersoft please resolve conflicts. Also the content for `TERM_WORKDIR_PARAMS` has changed. you might want to set it to `None`.

**Comment by rastersoft** [comment]
@Stunkymonkey Done.

**Comment by Stunkymonkey** [comment]
LGTM.

can you also please add it to the `README.md` list

**Comment by rastersoft** [comment]
Ops! You are right... Done.

**Pull request merged**
