### PR TITLE
Add support for Prompt

### PR DESCRIPTION
**Pull request by KyleGospo**
Adds support for [Prompt](https://gitlab.gnome.org/chergert/prompt), a new terminal emulator flatpak.

### CODE REVIEW

**Comment by Stunkymonkey** [comment]
can you please provide the cli arguments needed to start the terminal in a specific folder?

**Comment by KyleGospo** [comment]
For the current version:
`flatpak run org.gnome.Prompt.Devel --working-directory ~/Documents`

Stable is supposed to be out soon.

**Comment by KyleGospo** [comment]
@Stunkymonkey Had to add `NEW_WINDOW_PARAMS` for which Prompt is the only member due to a quirk where it'll focus the current window unless that's specified.

I have a local build re-based on PR #98, when that lands I'll update this PR to match.

**Comment by Stunkymonkey** [comment]
@KyleGospo PR #98 is merged. you can rebase now.

**Comment by KyleGospo** [comment]
@Stunkymonkey rebased, thanks!

**Comment by Stunkymonkey** [comment]
the failing CI is my mistake. Sorry

**Comment by Stunkymonkey** [comment]
While reviewing I got a new idea:

we should better have a dict in dict storing

`data = { "promt": {"name": "Promt", "new_window_args": "--abc"}, "foot": {"name": "Foot", ...}, ...}` to prevent the long lists.

But this is for me.

Thanks for your contribution.

**Pull request merged**
