### PR TITLE
Add flatpak support

### LINKED ISSUE #46: Support for Black Box
I'd love to see support added for the new terminal that has been talked about in a couple of places, [Black Box](https://gitlab.gnome.org/raggesilver/blackbox).

I imagine it would be troublesome to add support for it tho, considering it's the first time I'm aware of a flatpak'd terminal, I'm not sure of how hard it would be to have it work.

### PR DESCRIPTION
**Pull request by polyjitter**
Added a system for flatpak support, as flatpak versions of commands are different.

This fixes #46.

### CODE REVIEW

**Comment by polyjitter** [comment]
Doesn't actually open the working directory, not sure why. Will investigate further.

**Comment by polyjitter** [comment]
Actually, never mind, the Flathub install of Black Box just doesn't have the working directory functionality yet. This will most likely work once it does, but until it does, I don't think I can test.

@raggesilver Do you think it could be possible to get a flatpak update on flathub to get this functionality pushed out?

**Comment by polyjitter** [comment]
Actually, that's not the issue either... I'm genuinely kinda stumped as to why this isn't working.

**Comment by Stunkymonkey** [comment]
I do not like the current approach. Please add a new gschema-option: `use-flatpack`.

In your exact scenario this would be fine. But this will introduce unknown behavior if it is installed locally and via flatpack.

**Comment by polyjitter** [comment]
Out of scope for my skills, unfortunately.

**Comment by polyjitter** [comment]
Spoke too soon!

**Comment by polyjitter** [comment]
Hey, just wanted to say that this should be finished as per your requests to modify it :)

**Comment by phucnoob** [comment]
Does this work with blackbox yet?
i tried to set to blackbox but it seems to fallback to gnome-terminal
Tested on fedora 36 with blackbox 0.10.1

**Comment by Radical4ever** [comment]
Works great!!

**Comment by sk22** [comment]
disclaimer: i'm pretty positive that this isn't a problem of this PR, but it just occurred to me trying to switch from the user-scope pip install to the installation through setup.py.

not sure how exactly compiling the dconf schema works under the hood, but i ended up with nautilus crashing because:

```
Settings schema 'com.github.stunkymonkey.nautilus-open-any-terminal' does not contain a key named 'use-flatpak'
```

thing is, i installed nautilus-open-any-terminal first using "pip install --user" and then uninstalled it using pip (leaving the user-scoped schema in place, i guess?). now to test this fork, i ran "sudo ./setup.py install", which installed the python package system-wide and asked me to recompile the system-wide dconf schema (again, leaving the user dconf schema in place).
apparently, running "glib-compile-schemas ~/.local/share/glib-2.0/schemas/" fixed this for me, output was:

```
No schema files found: removed existing output file.
```

maybe this is something setup.py should handle, @Stunkymonkey?

**Comment by sk22** [comment]
> Does this work with blackbox yet? i tried to set to blackbox but it seems to fallback to gnome-terminal Tested on fedora 36 with blackbox 0.10.1

it does for me!

**Comment by Radical4ever** [comment]
maybe you need to full uninstall the old version (stunkymonkey one) and install the extension from the pull request

**Comment by sk22** [comment]
> maybe you need to full uninstall the old version (stunkymonkey one) and install the extension from the pull request

i did uninstall the stunkymonkey version using pip, which i assume left the dconf schema in place…
actually, i just noticed i didn’t see the readme’s uninstall section, so my bad!

**Comment by DeadMozay** [comment]
flatpak can be used in user space, so you still need to consider the key `--user`

`flatpak --user run com.raggesilver.BlackBox`

**Comment by Klapstuhl** [comment]
I have reworked this PR to support flatpaks system and user mode [here](https://github.com/Klapstuhl/nautilus-open-any-terminal/tree/flatpak).

As this PR has been sitting here for quiet some time, should i open a new PR?

**Comment by phucnoob** [comment]
> I have reworked this PR to support flatpaks system and user mode [here](https://github.com/Klapstuhl/nautilus-open-any-terminal/tree/flatpak).
> 
> As this PR has been sitting here for quiet some time, should i open a new PR?

No idea..

**Comment by phucnoob** [comment]
Any way, i have made this [extension](https://github.com/phucnoob/OpenInBlackBox) 
This specific for Blackbox only

**Comment by Stunkymonkey** [comment]
> I have reworked this PR to support flatpaks system and user mode [here](https://github.com/Klapstuhl/nautilus-open-any-terminal/tree/flatpak).
> 
> As this PR has been sitting here for quiet some time, should i open a new PR?

@Klapstuhl I would appreciate you opening a new PR.

**Comment by Stunkymonkey** [comment]
closed via #60

**Pull request closed without merging**
