### PR TITLE
Adds support for Terminator

### PR DESCRIPTION
**Pull request by baymax42**
I've added support for the Terminator terminal. It just adds Terminator key into the `TERM_PARAMS`.

### CODE REVIEW

**Comment by Stunkymonkey** [comment]
thanks for the PR.
is it really wanted to have `--new-tab` in the command? or is this just a personal thing?

**Comment by Stunkymonkey** [comment]
and it would be nice to have the terminal-names in alphabetical order.

**Comment by baymax42** [comment]
> 
> 
> thanks for the PR.
> is it really wanted to have `--new-tab` in the command? or is this just a personal thing?

TBH, my personal thing. I just don't like opening a lot of terminal windows. Can't say if it's wanted by rest of the people. I guess I'll remove that then.

**Comment by Stunkymonkey** [comment]
thanks for your PR
i plan to release a new version this week.

**Comment by Stunkymonkey** [comment]
i will also add an `--new-tab` option for you.

**Comment by Stunkymonkey** [comment]
@baymax42 sorry for taking so long.
Finally it is implemented.
just have a look at the new options via `dconf`

**Pull request merged**
