### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by lvxnull**

### CODE REVIEW

**Comment by Stunkymonkey** [comment]
what do you think about: #141

**Comment by lvxnull** [comment]
That adds another dependency for a minor convenience. Let's merge this one first and decide for the next release if we want #141 or not.

**Comment by lvxnull** [comment]
Would it be bad if I just force pushed the tag?

**Comment by Stunkymonkey** [comment]
If it would be days ago, I would complain, that package manager would have picked up the "new release" and ignore the next. But lets just move along.

**Review by Stunkymonkey — APPROVED** [review]

**Comment by Stunkymonkey** [comment]
perfect. thanks

works: https://github.com/Stunkymonkey/nautilus-open-any-terminal/actions/runs/8072618630

**Pull request merged**
