### PR TITLE
Implement script execution

### LINKED ISSUE #164: Run Script in (terminal) when right-clicking on a script [feature request]
Tilix's nautilus integration (in which nautilus-open-any-terminal seems based) supports showing a "Run Script in Tilix" context menu entry in nautilus that runs the script in a new tab in tilix, when right clicking on an executable script (or on a symbolic link to executable script)

This is a feature request to add that function generically to the selected terminal in nautilus-open-any-terminal

### PR DESCRIPTION
**Pull request by lvxnull**
Fixes #164

### CODE REVIEW

**Comment by Stunkymonkey** [comment]
oh no. I completely forgot about this one...

Sorry for the wait.

**Review by Stunkymonkey — COMMENTED** [review]
I am impressed by the implementation. You have some good coding skills. No complains about the code. Thanks you very much contributing.

Sadly the whole extension stops working for me and no context-entry is not shown...

**Comment by lvxnull** [comment]
Have you compiled the schema?

**Comment by Stunkymonkey** [comment]
> Have you compiled the schema?

do i have to? the xml for gconf did not change. will try tomorrow

**Comment by lvxnull** [comment]
That was an issue i found while testing on a VM, otherwise the extension works

**Comment by Stunkymonkey** [comment]
ok sorry. this was my mistake. I can confirm it works for multiple terminals, except for `foot` with the following crash:

```
warn: fcft.c:583: failed to get full font name
```

but this might be a nixos problem itself: https://discourse.nixos.org/t/sway-crash-when-in-full-screen-and-opening-a-foot-terminal/42207

so all good from my POV

**Review by Stunkymonkey — APPROVED** [review]

**Pull request merged**
