### PR TITLE
bugfix: multi language not work

### LINKED ISSUE #75: multi language doesn't work
When I set my locale to `de_AT` I found it doesn't work, while other items has been changed to German. Could you help me to solve the trouble? Anything else should I do?

* Debian 11
* nautilus version: 3.38.2
* python3-nautilus: 1.2.3-3
* nautilus-open-any-terminal: 0.4.0
* locale:
```sh
$ locale
LANG=de_AT.UTF-8
LANGUAGE=
LC_CTYPE="de_AT.UTF-8"
LC_NUMERIC="de_AT.UTF-8"
LC_TIME=en_US.UTF-8
LC_COLLATE="de_AT.UTF-8"
LC_MONETARY="de_AT.UTF-8"
LC_MESSAGES=de_AT.UTF-8
LC_PAPER="de_AT.UTF-8"
LC_NAME="de_AT.UTF-8"
LC_ADDRESS="de_AT.UTF-8"
LC_TELEPHONE="de_AT.UTF-8"
LC_MEASUREMENT="de_AT.UTF-8"
LC_IDENTIFICATION="de_AT.UTF-8"
LC_ALL=
```

### PR DESCRIPTION
**Pull request by BenSYZ**
* fixed #75 
* add translation: `zh_CN`

### CODE REVIEW

**Comment by BenSYZ** [comment]
I'm not profession at python, so if there is a better way to solve it, please do so.

**Comment by Stunkymonkey** [comment]
have you tested this? I see many pushes, so I want to be certain you are not developing any more.

**Comment by BenSYZ** [comment]
Yes. I've test it. Because I didn't enable action in my repository, the shell scripts were not written properly, which leads to many pushes.

**Comment by Stunkymonkey** [comment]
thanks a lot for your contribution.
first execution works without any problems.
will continue my testing on the weekend

**Comment by Stunkymonkey** [comment]
Nice work :+1:
missing problem fixed and a new language is added. Could not ask for anything more.

**Pull request merged**
