### PR TITLE
Integrate Tabby.sh

### PR DESCRIPTION
**Pull request by bumbummen99**
Integrate Tabby.sh

- [x] Open in directory (https://github.com/Eugeny/tabby/issues/6540)
- [ ] Open new tab

### CODE REVIEW

**Comment by Stunkymonkey** [comment]
please also add it to the [README.md](https://github.com/Stunkymonkey/nautilus-open-any-terminal#supported-terminal-emulators=)

**Comment by Stunkymonkey** [comment]
thanks for your contribution. is it ready to get merged? then please set it accordingly. Otherwise i can not merge the PR.

**Comment by bumbummen99** [comment]
> thanks for your contribution. is it ready to get merged? then please set it accordingly. Otherwise i can not merge the PR.

No it is not done at all. Tabby offers the `open` command to open *here* - it works on windows only right now so i can not test it.
Also it does not seem to have a tab command but that does not seem mandatory. Still, without the open command working on Linux too this is not worth anything as it just opens the tabby window.

**Comment by bumbummen99** [comment]
@Stunkymonkey Alright, i got to test it now and it does work tho the user has to manually create an precending or overwrite the PATH for tabby as the default script installed by Repository does not redirect CLI arguments.

**Comment by bumbummen99** [comment]
To install Tabby, fix the PATH script and add as update-alternative for default terminal (Ctrl+Alt+T).
```bash
curl -s https://packagecloud.io/install/repositories/eugeny/tabby/script.deb.sh | sudo bash && \
sudo ln -s /opt/Tabby/tabby /usr/local/bin/tabby && \
sudo chown root:root /usr/local/bin/tabby && \
sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/tabby 50
```

To change default terminal (Ctrl+Alt+T)
`sudo update-alternatives --config x-terminal-emulator`

**Comment by Stunkymonkey** [comment]
nice to know. Thanks for your work :tada:

**Pull request merged**
