### PR TITLE
update super-linter 5 -> 6

### PR DESCRIPTION
**Pull request by Stunkymonkey**
update to the new CI workflow. see the checks.

### CODE REVIEW

**Comment by lvxnull** [comment]
Is the new version of this any faster? I hate that it tries to check every single file in the repo with a "copy paste detector" and takes a horrendously long amount of time to even start. Can't we just run black/isort/pylint ourselves instead of relying on this?

**Comment by Stunkymonkey** [comment]
@lvxnull new version prints the status of each linter in a separate check.

Yes we could write this our own, and yes we would forget about new linters. So to be up-to-date with linters I think this is a nice way.

**Review by lvxnull — APPROVED** [review]
I don't like super-linter, but updating it wouldn't hurt.

**Comment by Stunkymonkey** [comment]
rebased, but changed the last commit.

I totaly agree, that the linters do not need constant updates. What I really like about it: Not having to care about adding new linters for various things.
But I guess we just have a different opinion on this.

If you want to we could add an additional black, pylint and isort to have faster feedback (not sure if this is in your mind; feels more like you hate the waiting-time).

Btw: The Linter is not a required Job (only the python build is). It only helps guiding.

**Review by lvxnull — APPROVED** [review]

**Pull request merged**
