### PR TITLE
Makefile: respect DESTDIR

### PR DESCRIPTION
**Pull request by WavyEbuilder**
Currently, the Makefile does not support DESTDIR. This pr fixes that.

### CODE REVIEW

**Comment by lvxnull** [comment]
I have a few problems with this:
- the locale Makefile still ignores DESTDIR
- PREFIX is still set to `$HOME/.local` when not running as root
- I didn't test it, but I don't think `DESTDIR ?= ` is required here

**Review by lvxnull — CHANGES_REQUESTED** [review]
I have a few problems with this:
- the locale Makefile still ignores DESTDIR
- PREFIX is still set to `$HOME/.local` when not running as root
- I didn't test it, but I don't think `DESTDIR ?= ` is required here

**Comment by WavyEbuilder** [comment]
Good points, will fix now!

**Comment by lvxnull** [comment]
If someone is running as non-root and sets DESTDIR to something, say `/test/path`, then the actual installation path will be `/test/path/home/$USER/.local`, which might be confusing. I think it would be better if instead PREFIX was set to `/.local` if running as non-root and DESTDIR is unset, otherwise to `/usr`, and default `DESTDIR` to `$HOME` if running as non-root.

**Comment by WavyEbuilder** [comment]
Ah thanks for that! I'll fix that now :)

**Comment by lvxnull** [comment]
I think you could just write `export DESTDIR` instead of passing it explicitly in arguments

**Comment by WavyEbuilder** [comment]
Will check and report back later

**Comment by lvxnull** [comment]
I wanted to implement this feature sooner but i never found time to do it.
Once im home I'll make a new PR.

**Comment by lvxnull** [comment]
Already implemented in #156

**Comment by JulianVennen** [comment]
Thanks :)

**Pull request closed without merging**
